### ISSUE TITLE
‘ timestamp ’ needs to be added after chrome version 99

### ISSUE THREAD

**Issue by AndySkaura** [yak0/media-composer#1]
https://developer.chrome.com/blog/deps-rems-99/#update-webcodecs-to-match-the-specification
![image](https://user-images.githubusercontent.com/26220564/188533110-a902c161-70c1-4490-b3ae-e9a009828da9.png)

**Comment by AndySkaura** [comment]
Thank you for your project. It helped me a lot.

**Comment by rhwilburn** [comment]
I see this on Chrome 125 on Windows (64 bit).

```
worker.js:71 Uncaught (in promise) 
TypeError: Failed to construct 'VideoFrame': VideoFrameInit must provide timestamp
    at Object.transform (worker.js:71:26)
```

**Comment by rhwilburn** [comment]
@yak0 Please merge in if you feel it makes sense

**Comment by yak0** [comment]
@rhwilburn thank you for your contribution.
